name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Create env file
        run: |
          touch .env
          echo VITE_API_KEY=$VITE_API_KEY >> .env
          echo VITE_API_HOST=$VITE_API_HOST >> .env
          cat .env
        # env:
        #   VITE_API_KEY: ${{ vars.VITE_API_KEY }}
        #   VITE_API_HOST: ${{ vars.VITE_API_HOST }}
      - name: Build app
        run: |
          npm install
          npm run-script build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1

